
import os
import sys
import time
import subprocess
import requests
import json

# Import existing steps
from keycloak_setup import setup_keycloak
from grant_exchange_v3 import grant_exchange_v3

from keycloak import KeycloakAdmin

def check_health(timeout=60):
    print("--- Checking Keycloak Health ---")
    url = "http://localhost:8080/realms/master"
    start = time.time()
    while time.time() - start < timeout:
        try:
            resp = requests.get(url)
            if resp.status_code == 200:
                print("✅ Keycloak is UP!")
                return True
        except:
            pass
        time.sleep(2)
        print(".", end="", flush=True)
    print("\n❌ Keycloak timed out.")
    return False

def setup_client_registration():
    print("\n--- Registering Application Client ---")
    # We need to manually register 'test-module-agent-v3' if it doesn't exist.
    # We can use the IAT generated by keycloak_setup.py
    
    SERVER = "http://localhost:8080"
    REALM = "agent-mesh"
    CLIENT_ID = "test-module-agent-v3"
    
    # 1. Check if client exists via Admin API
    ka = KeycloakAdmin(server_url=SERVER + "/",
                       username="admin",
                       password="admin",
                       realm_name=REALM,
                       user_realm_name="master",
                       verify=False)
    
    existing_id = ka.get_client_id(CLIENT_ID)
    if existing_id:
        print(f"⚠️  Client {CLIENT_ID} exists. Deleting to ensure clean state...")
        ka.delete_client(existing_id)

    # 2. Register new
    try:
        iat_path = "iat.txt"
        with open(iat_path) as f:
            iat = f.read().strip()
            
        print(f"Registering {CLIENT_ID} using IAT...")
        headers = {
            "Authorization": f"Bearer {iat}",
            "Content-Type": "application/json"
        }
        payload = {
            "clientId": CLIENT_ID,
            "secret": "very-secret-agent-secret", # Hardcoding for stability in POC
            "redirectUris": [],
            "serviceAccountsEnabled": True,
            "authorizationServicesEnabled": True,
            "standardFlowEnabled": False,
            "directAccessGrantsEnabled": False
        }
        
        url = f"{SERVER}/realms/{REALM}/clients-registrations/default"
        resp = requests.post(url, json=payload, headers=headers)
        
        if resp.status_code == 201:
            print(f"✅ Successfully registered {CLIENT_ID}")
            # Save creds for test module
            data = resp.json()
            secret = data.get("secret")
            if not secret:
                 print("⚠️  No secret returned in registration response! Using requested one.")
                 secret = "very-secret-agent-secret"
                 
            creds_path = os.path.join(os.path.dirname(__file__), "test_module_creds.json")
            with open(creds_path, "w") as f:
                json.dump({
                    "client_id": CLIENT_ID,
                    "client_secret": secret
                }, f)
        else:
            print(f"❌ Registration failed: {resp.status_code} {resp.text}")

    except Exception as e:
        print(f"⚠️  Registration error: {e}")


def setup_audience():
    print("\n--- Configuring Audience Mapper ---")
    ka = KeycloakAdmin(server_url="http://localhost:8080/",
                       username="admin",
                       password="admin",
                       realm_name="agent-mesh",
                       user_realm_name="master",
                       verify=False)

    SOURCE_CLIENT_ID = "test-client"
    TARGET_AUDIENCE = "test-module-agent-v3"
    
    try:
        source_uuid = ka.get_client_id(SOURCE_CLIENT_ID)
        if not source_uuid:
            print(f"❌ Source client {SOURCE_CLIENT_ID} not found.")
            return

        # Check if mapper exists
        # Correct method: get_mappers_from_client(client_id)
        mappers = ka.get_mappers_from_client(source_uuid)
        for m in mappers:
            if m['name'] == f"Audience for {TARGET_AUDIENCE}":
                 print(f"✅ Audience Mapper already exists.")
                 return

        mapper_payload = {
            "name": f"Audience for {TARGET_AUDIENCE}",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-audience-mapper",
            "consentRequired": False,
            "config": {
                "included.client.audience": TARGET_AUDIENCE,
                "id.token.claim": "true",
                "access.token.claim": "true"
            }
        }
        ka.add_mapper_to_client(source_uuid, mapper_payload)
        print(f"✅ Audience Mapper added to {SOURCE_CLIENT_ID}")
    except Exception as e:
        print(f"⚠️  Failed to setup audience: {e}")

def setup_script_mapper():
    print("\n--- Configuring Dynamic Actor Claim Mapper ---")
    ka = KeycloakAdmin(server_url="http://localhost:8080/",
                       username="admin",
                       password="admin",
                       realm_name="agent-mesh",
                       user_realm_name="master",
                       verify=False)
                       
    TARGET_CLIENT = "test-module-agent-v3"
    
    try:
        client_id = ka.get_client_id(TARGET_CLIENT)
        if not client_id:
            print(f"❌ Client {TARGET_CLIENT} not found.")
            return

        # Check if mapper exists
        mappers = ka.get_mappers_from_client(client_id)
        for m in mappers:
            if m['name'] == "Dynamic Actor Claim":
                print("✅ Script Mapper already exists.")
                return

        mapper_payload = {
            "name": "Dynamic Actor Claim",
            "protocol": "openid-connect",
            "protocolMapper": "script-act-mapper.js", # Depends on JAR deployment
            "consentRequired": False,
            "config": {
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true",
                "multivalued": "false"
            }
        }
        
        ka.add_mapper_to_client(client_id, mapper_payload)
        print(f"✅ Script Mapper added to {TARGET_CLIENT}")
        
    except Exception as e:
        if "ProtocolMapper provider not found" in str(e):
             print("❌ Script Provider JAR not loaded! Did you mount 'dynamic-mapper.jar'?")
        print(f"⚠️  Failed to add script mapper: {e}")


def main():
    print("===========================================")
    print("   SecureAgent POC - Automated Setup")
    print("===========================================")
    
    # 1. Health Check
    if not check_health():
        sys.exit(1)
        
    # 2. Realm/User/Client Setup
    print("\n--- 1. Setting up Realm & Users ---")
    setup_keycloak()
    
    # 3. Register Application Client
    setup_client_registration()
    
    # 4. Permissions (Policy) Setup
    print("\n--- 2. Granting Token Exchange Permissions ---")
    grant_exchange_v3()
    
    # 5. Audience Setup
    print("\n--- 3. Fixing Audience ---")
    setup_audience()
    
    # 6. Dynamic Mapper Setup
    print("\n--- 4. Enabling Dynamic 'act' Claim ---")
    setup_script_mapper()
    
    print("\n✅ Setup Complete! You can now run 'python test_module.py'")

if __name__ == "__main__":
    main()
